spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game_service
    username: root
    password: Minhanh010103
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  storage:
    upload-dir: uploads/


